### ISSUE TITLE
[edukit_comparefiles] bring comparefiles from L4A repo

### ISSUE THREAD

**Issue by dianagold** [worldbank/EduAnalyticsToolkit#4]

**Comment by kbjarkefur** [comment]
I have moved the file as of 4a7eadcd552b6260bb22b37cdd10b9990583a184 , but I have not yet deleted it from https://github.com/worldbank/Learning4all as I have not yet tested that all locations in the code in the L4A repo has been updated.

**Comment by kbjarkefur** [comment]
Done as of #11
