### ISSUE TITLE
[images] an easy way to add images to the repo

### ISSUE THREAD

**Issue by dianagold** [worldbank/EduAnalyticsToolkit#9]
Inspired by [this post](https://ardalis.com/add-images-easily-to-github).
Logo for EduAnalytics
![image](https://user-images.githubusercontent.com/43160181/62169131-58ea6a00-b2f5-11e9-977f-18117cc9e42d.png)

**Comment by kbjarkefur** [comment]
This is a cool trick. Maybe you figured that out and posted anyway to notify the rest of us, but you do not have to post the issue for this trick to work. As soon as the URL appears in the text box you can copy and use it, even if you discard the issue. 

On the other hand, having one issue like this where we keep adding images we want to use in the repo is a good way to keep them in one place so we all know where we have already created links to images and therefore do not have to duplicate it. Maybe you thought of that too already.
